Repository rabbitmq/khepri, pull requests merged in 2022-02, with the labels that each got.

#34 Various small improvements
  src/khepri_fun.erl
Labels: enhancement

#35 khepri_fun: Support `try` instruction
  src/khepri_fun.erl
Labels: enhancement

#36 khepri_fun: Add guessed `var_info` annotations to assembly
  src/khepri_fun.erl
  test/mod_used_for_transactions.erl
  test/tx_funs.erl
Labels: bug

#37 Support more instructions
  src/khepri_fun.erl
  src/khepri_tx.erl
  test/tx_funs.erl
Labels: enhancement

#39 khepri_fun: Patch incorrectly decoded instructions
  src/khepri_fun.erl
  src/khepri_tx.erl
  test/tx_funs.erl
Labels: enhancement

#41 Transactions: Allow `re` module
  src/khepri_tx.erl
  test/tx_funs.erl
Labels: enhancement

#8 Added plugin rebar3_edoc_extensions
  .gitignore
  README.md
  doc/README.md
  rebar.config
  src/edoc.hrl
  src/khepri_edoc_export.erl
  src/khepri_edoc_wrapper.erl
Labels: documentation

#42 Rebar: Follow-up to the addition of rebar3_edoc_extensions
  doc/github-markdown.css
  doc/prism.css
  doc/prism.js
  rebar.config
Labels: documentation

#38 rewrite case labels in select_tuple_arity instruction
  src/khepri_fun.erl
  test/tx_funs.erl
Labels: enhancement

#40 patch more incorrectly decoded bitstring-matching instructions
  src/khepri_fun.erl
  src/khepri_tx.erl
  test/tx_funs.erl
Labels: enhancement

#51 Decode "Line" chunk and expand `line` instructions
  src/khepri_fun.erl
  test/mod_used_for_transactions.erl
  test/stored_procs.erl
Labels: enhancement

#55 khepri_fun: Complete "Line" beam chunk decoding
  src/khepri_fun.erl
  test/line_chunk.erl
Labels: enhancement

#54 khepri_fun: Add `select_tuple_arity` type annotation
  src/khepri_fun.erl
  test/tx_funs.erl
Labels: enhancement
