Repository rabbitmq/khepri, pull requests merged in 2022-04, with the labels that each got.

#74 khepri_path: Change syntax of string-based paths
  src/khepri_path.erl
  test/path_operations.erl
  test/prop_path_operations.erl
Labels: enhancement

#72 khepri_fun: Cache compiled standalone function
  src/khepri_fun.erl
  test/sf_cache.erl
Labels: enhancement

#76 Fix how dual licensing is applied
  LICENSE
  LICENSE.Apache-2.0
  LICENSE.MPL-2.0
  README.md
  src/khepri.app.src
Labels: documentation

#84 Fix typo handling deleted nodes on aftermath
  src/khepri_machine.erl
  test/keep_while_conditions.erl
Labels: bug

#79 Revamp public API
  README.md
  doc/overview.edoc
  include/khepri.hrl
  src/internal.hrl
  src/khepri.erl
  src/khepri_app.erl
  src/khepri_cluster.erl
  src/khepri_condition.erl
  src/khepri_evf.erl
  src/khepri_fun.erl
  src/khepri_fun.hrl
  src/khepri_machine.erl
  src/khepri_machine.hrl
  src/khepri_payload.erl
  src/khepri_sproc.erl
  src/khepri_tx.erl
  src/khepri_utils.erl
  test/async_option.erl
  test/conditions.erl
  test/db_info.erl
  test/delete_command.erl
  test/display_tree.erl
  test/favor_option.erl
  test/keep_while_conditions.erl
  test/machine_code_called_from_ra.erl
  test/prop_state_machine.erl
  test/put_command.erl
  test/queries.erl
  test/root_node.erl
  test/sf_cache.erl
  test/simple_delete.erl
  test/simple_get.erl
  test/simple_put.erl
  test/stored_procs.erl
  test/test_ra_server_helpers.erl
  test/transactions.erl
  test/triggers.erl
  test/tx_funs.erl
Labels: documentation, enhancement

#90 khepri: Add `get_data_or/{2,3,4}`
  src/khepri.erl
  src/khepri_tx.erl
  test/simple_get.erl
  test/transactions.erl
Labels: enhancement
