Repository rabbitmq/khepri, pull requests merged in 2022-11, with the labels that each got.

#159 Implement ra_machine:overview/1 for khepri_machine
  src/khepri_fun.erl
  src/khepri_machine.erl
  src/khepri_utils.erl
  test/display_tree.erl
Labels: enhancement

#161 Fix `call_fun2` instruction jump label support
  src/khepri_fun.erl
  src/khepri_tx_adv.erl
  test/mod_used_for_transactions.erl
  test/tx_funs.erl
Labels: bug

#157 Add import/export feature
  rebar.config
  src/khepri.erl
  src/khepri_export_erlang.erl
  src/khepri_import_export.erl
  src/khepri_machine.erl
  test/export.erl
  test/export_erlang.erl
  test/export_helper.erl
Labels: enhancement

#164 Rename `delete_payload()` back to `clear_payload()`
  src/khepri.erl
  src/khepri_adv.erl
  src/khepri_bang.hrl
  src/khepri_tx.erl
  src/khepri_tx_adv.erl
  test/advanced_delete.erl
  test/advanced_tx_delete.erl
  test/bang_functions.erl
  test/cluster_SUITE.erl
  test/simple_delete.erl
  test/simple_tx_delete.erl
Labels: enhancement

#166 khepri_machine: Merge `extra` into `options` in `#put{}` command
  src/khepri_import_export.erl
  src/khepri_machine.erl
  src/khepri_machine.hrl
  src/khepri_tx_adv.erl
  test/export.erl
  test/export_erlang.erl
  test/keep_while_conditions.erl
Labels: enhancement

#167 khepri_cluster: Accept `machine_config` in Ra server config
  src/khepri_cluster.erl
  test/cluster_SUITE.erl
Labels: enhancement

#169 tx_funs: Test bitstring matching with field flags
  test/tx_funs.erl
Labels: enhancement

#135 Add projections
  doc/overview.edoc
  rebar.config
  rebar.lock
  src/khepri.erl
  src/khepri_machine.erl
  src/khepri_machine.hrl
  src/khepri_projection.erl
  src/khepri_projection.hrl
  src/khepri_tx_adv.erl
  test/cluster_SUITE.erl
  test/projections.erl
  test/test_ra_server_helpers.erl
Labels: enhancement

#173 Documentation: Briefly talk about import/export in overview page
  doc/overview.edoc
Labels: documentation

#174 Fix supervision tree shutdown
  src/khepri.app.src
  src/khepri_event_handler.erl
Labels: bug
